# Numpy Basics

In [ ]:
import numpy as np

In [2]:
n=np.array([1,2,3,4])
a2=np.array([[2,3],[6,7]])
a3=np.array([[5,6],[8,7]])
a=np.array([[5,6,7,8],[9,10,11,12],[13,2,3,4]])
b=np.array([2.4,1.5,6.4],dtype=complex)
o=np.zeros((3,3))
a1=np.ones((3,3))


In [116]:
#index give 
a[2][0]

13

In [117]:
#print dimension
a.ndim

2

In [118]:
n.ndim

1

In [119]:
#print size of array int,float ,etc
n.itemsize

4

In [120]:
b.itemsize

16

In [121]:
#print how many number in array
b.size

3

In [122]:
#print row and column
a.shape

(3, 4)

In [123]:
b

array([2.4+0.j, 1.5+0.j, 6.4+0.j])

In [124]:
o

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [125]:
a1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [126]:
#give range in list
l=range(5)
l

range(0, 5)

In [127]:
l[2]

2

In [141]:
#give range in array
np.arange(1,5)


array([1, 2, 3, 4])

In [143]:
np.arange(1,10,2) # number of steps


array([1, 3, 5, 7, 9])

In [144]:
np.linspace(1,5,10) #number of print number

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [131]:
#reshape the matrix
a.reshape(4,3)

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [ 2,  3,  4]])

In [145]:
#print maximum number in array
a.max()

13

In [146]:
#print minimum number in array
a.min()

2

In [147]:
#sum array value
n.sum()

10

In [188]:
a2.sum(axis=0) #axis=0 sum column or verticale

array([ 8, 10, 13])

In [186]:
a2.sum(axis=1)

array([10, 21])

In [197]:
a0=np.array([[9,2,3],[4,5,6],[7,8,9]])
a0

array([[9, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [198]:
#take the deteminant
d=np.linalg.det(a0)
d

-24.000000000000068

In [199]:
#taking sqaure root in array elements
np.sqrt(a0)


array([[3.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [200]:
#standard derivation
np.std(a0)

2.4241582476968255

In [222]:
a3

array([[5, 6],
       [8, 7]])

In [223]:
#sum both matrix elements
a2+a3

array([[ 7,  9],
       [14, 14]])

In [224]:
#minus both matrix elements
a3-a2

array([[3, 3],
       [2, 0]])

In [225]:
#multiply both matrix elements
a2*a3

array([[10, 18],
       [48, 49]])

In [226]:
#division both matrix elements
a2/a3

array([[0.4 , 0.5 ],
       [0.75, 1.  ]])

In [227]:
#product of matrix
a2.dot(a3)

array([[34, 33],
       [86, 85]])

In [3]:
#numpy slicing/stacking and indexing with boolean array
a

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13,  2,  3,  4]])

In [4]:
a[0,2]

7

In [7]:
a[0:2,2]

array([ 7, 11])

In [8]:
a[-1]

array([13,  2,  3,  4])

In [15]:
a[:,0:2]

array([[ 5,  6],
       [ 9, 10],
       [13,  2]])

In [16]:
for i in a:
    print(i)

[5 6 7 8]
[ 9 10 11 12]
[13  2  3  4]


In [17]:
for cell in  a.flat:
    print(cell)

5
6
7
8
9
10
11
12
13
2
3
4


In [37]:
#add two array in one array
w=np.vstack((a2,a3))   #vertical add array
w

array([[2, 3],
       [6, 7],
       [5, 6],
       [8, 7]])

In [38]:
w2=np.hstack((a2,a3)) #horizental add array
w2

array([[2, 3, 5, 6],
       [6, 7, 8, 7]])

In [59]:
#horizental break and print
s=np.arange(30).reshape(2,15)
s

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [60]:
result=np.hsplit(s,3) # break in 3 parts
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [61]:
result[0] #one part  output

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [62]:
result[2] #third part output

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [63]:
#now vertically break and output
result2=np.vsplit(s,2)
result2

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [64]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [66]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [85]:
b3=np.arange(12).reshape(3,4)
b3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
b4=b3>4
b4

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [88]:
b3[b4]

array([ 5,  6,  7,  8,  9, 10, 11])

In [93]:
b3[b4]=-5
b3

array([[ 0,  1,  2,  3],
       [ 4, -5, -5, -5],
       [-5, -5, -5, -5]])

In [95]:
#save and load file
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
np.savetxt("Save.txt",x)

In [103]:
y=np.loadtxt('Save.txt')
y

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [105]:
for i in x.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [3]:
a=np.array([[1,2,3],[5,6,7],[9,10,11]])
a1=np.array([[1,2,3],[4,5,6]])
a3=np.array([[2,3],[4,5]])
a2=np.array([[3,4,5],[7,8,9]])
a.ndim
a.size
# a.itemsize
# np.sqrt(a)
# np.linspace(1,5,10)
# a3.dot(a1)
# a.max()
# a.min()
# a.sum()
# a3.sum(axis=0)
# a3.sum(axis=1)
# np.linalg.det(a)
# np.std(a)
# np.mean(a)
# a1+a2
# a2-a1
# a2*a1
# a1/a2
# a[0:3,2]
# for i in a:
#     print(i)
# for c in a.flat:
#     print(c)
# np.vstack((a1,a2))
# s=np.arange(20).reshape(4,5)
# result=np.vsplit(s,4)
# a4=a>5
# a[a4]=-6


9